// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/iroh_client.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  (int, int) dco_decode_box_autoadd_record_u_16_u_16(dynamic raw);

  @protected
  TerminalCreateRequest dco_decode_box_autoadd_terminal_create_request(
    dynamic raw,
  );

  @protected
  TerminalInputRequest dco_decode_box_autoadd_terminal_input_request(
    dynamic raw,
  );

  @protected
  TerminalResizeRequest dco_decode_box_autoadd_terminal_resize_request(
    dynamic raw,
  );

  @protected
  TerminalStopRequest dco_decode_box_autoadd_terminal_stop_request(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  (int, int)? dco_decode_opt_box_autoadd_record_u_16_u_16(dynamic raw);

  @protected
  (int, int) dco_decode_record_u_16_u_16(dynamic raw);

  @protected
  RustError dco_decode_rust_error(dynamic raw);

  @protected
  StreamEvent dco_decode_stream_event(dynamic raw);

  @protected
  TerminalCreateRequest dco_decode_terminal_create_request(dynamic raw);

  @protected
  TerminalInputRequest dco_decode_terminal_input_request(dynamic raw);

  @protected
  TerminalResizeRequest dco_decode_terminal_resize_request(dynamic raw);

  @protected
  TerminalStopRequest dco_decode_terminal_stop_request(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  (int, int) sse_decode_box_autoadd_record_u_16_u_16(
    SseDeserializer deserializer,
  );

  @protected
  TerminalCreateRequest sse_decode_box_autoadd_terminal_create_request(
    SseDeserializer deserializer,
  );

  @protected
  TerminalInputRequest sse_decode_box_autoadd_terminal_input_request(
    SseDeserializer deserializer,
  );

  @protected
  TerminalResizeRequest sse_decode_box_autoadd_terminal_resize_request(
    SseDeserializer deserializer,
  );

  @protected
  TerminalStopRequest sse_decode_box_autoadd_terminal_stop_request(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  (int, int)? sse_decode_opt_box_autoadd_record_u_16_u_16(
    SseDeserializer deserializer,
  );

  @protected
  (int, int) sse_decode_record_u_16_u_16(SseDeserializer deserializer);

  @protected
  RustError sse_decode_rust_error(SseDeserializer deserializer);

  @protected
  StreamEvent sse_decode_stream_event(SseDeserializer deserializer);

  @protected
  TerminalCreateRequest sse_decode_terminal_create_request(
    SseDeserializer deserializer,
  );

  @protected
  TerminalInputRequest sse_decode_terminal_input_request(
    SseDeserializer deserializer,
  );

  @protected
  TerminalResizeRequest sse_decode_terminal_resize_request(
    SseDeserializer deserializer,
  );

  @protected
  TerminalStopRequest sse_decode_terminal_stop_request(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_record_u_16_u_16(
    (int, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_terminal_create_request(
    TerminalCreateRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_terminal_input_request(
    TerminalInputRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_terminal_resize_request(
    TerminalResizeRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_terminal_stop_request(
    TerminalStopRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_record_u_16_u_16(
    (int, int)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_16_u_16((int, int) self, SseSerializer serializer);

  @protected
  void sse_encode_rust_error(RustError self, SseSerializer serializer);

  @protected
  void sse_encode_stream_event(StreamEvent self, SseSerializer serializer);

  @protected
  void sse_encode_terminal_create_request(
    TerminalCreateRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_terminal_input_request(
    TerminalInputRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_terminal_resize_request(
    TerminalResizeRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_terminal_stop_request(
    TerminalStopRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
