// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/iroh_client.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiIrohClientInitApp();
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 478359348;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_riterm',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiIrohClientConnectToPeer({
    required String sessionTicket,
  });

  Future<void> crateApiIrohClientCreateTerminal({
    required TerminalCreateRequest request,
  });

  Future<void> crateApiIrohClientDisconnectSession({required String sessionId});

  Future<List<String>> crateApiIrohClientGetActiveSessions();

  Future<StreamEvent> crateApiIrohClientGetEventStream({
    required String sessionId,
  });

  Future<String> crateApiIrohClientGetNodeInfo();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiIrohClientInitApp();

  Future<void> crateApiSimpleInitApp();

  Future<String> crateApiIrohClientInitializeNetwork();

  Future<String> crateApiIrohClientInitializeNetworkWithRelay({
    String? relayUrl,
  });

  Future<void> crateApiIrohClientListTerminals({required String sessionId});

  String crateApiIrohClientParseSessionTicket({required String ticket});

  Future<void> crateApiIrohClientResizeTerminal({
    required TerminalResizeRequest request,
  });

  Future<void> crateApiIrohClientSendTerminalInputToTerminal({
    required TerminalInputRequest request,
  });

  Future<void> crateApiIrohClientStopTerminal({
    required TerminalStopRequest request,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiIrohClientConnectToPeer({
    required String sessionTicket,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionTicket, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_rust_error,
        ),
        constMeta: kCrateApiIrohClientConnectToPeerConstMeta,
        argValues: [sessionTicket],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientConnectToPeerConstMeta =>
      const TaskConstMeta(
        debugName: "connect_to_peer",
        argNames: ["sessionTicket"],
      );

  @override
  Future<void> crateApiIrohClientCreateTerminal({
    required TerminalCreateRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_terminal_create_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_rust_error,
        ),
        constMeta: kCrateApiIrohClientCreateTerminalConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientCreateTerminalConstMeta =>
      const TaskConstMeta(debugName: "create_terminal", argNames: ["request"]);

  @override
  Future<void> crateApiIrohClientDisconnectSession({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_rust_error,
        ),
        constMeta: kCrateApiIrohClientDisconnectSessionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientDisconnectSessionConstMeta =>
      const TaskConstMeta(
        debugName: "disconnect_session",
        argNames: ["sessionId"],
      );

  @override
  Future<List<String>> crateApiIrohClientGetActiveSessions() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_rust_error,
        ),
        constMeta: kCrateApiIrohClientGetActiveSessionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientGetActiveSessionsConstMeta =>
      const TaskConstMeta(debugName: "get_active_sessions", argNames: []);

  @override
  Future<StreamEvent> crateApiIrohClientGetEventStream({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stream_event,
          decodeErrorData: sse_decode_rust_error,
        ),
        constMeta: kCrateApiIrohClientGetEventStreamConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientGetEventStreamConstMeta =>
      const TaskConstMeta(
        debugName: "get_event_stream",
        argNames: ["sessionId"],
      );

  @override
  Future<String> crateApiIrohClientGetNodeInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_rust_error,
        ),
        constMeta: kCrateApiIrohClientGetNodeInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientGetNodeInfoConstMeta =>
      const TaskConstMeta(debugName: "get_node_info", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiIrohClientInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIrohClientInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiIrohClientInitializeNetwork() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_rust_error,
        ),
        constMeta: kCrateApiIrohClientInitializeNetworkConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientInitializeNetworkConstMeta =>
      const TaskConstMeta(debugName: "initialize_network", argNames: []);

  @override
  Future<String> crateApiIrohClientInitializeNetworkWithRelay({
    String? relayUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(relayUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_rust_error,
        ),
        constMeta: kCrateApiIrohClientInitializeNetworkWithRelayConstMeta,
        argValues: [relayUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientInitializeNetworkWithRelayConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_network_with_relay",
        argNames: ["relayUrl"],
      );

  @override
  Future<void> crateApiIrohClientListTerminals({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_rust_error,
        ),
        constMeta: kCrateApiIrohClientListTerminalsConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientListTerminalsConstMeta =>
      const TaskConstMeta(debugName: "list_terminals", argNames: ["sessionId"]);

  @override
  String crateApiIrohClientParseSessionTicket({required String ticket}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ticket, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_rust_error,
        ),
        constMeta: kCrateApiIrohClientParseSessionTicketConstMeta,
        argValues: [ticket],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientParseSessionTicketConstMeta =>
      const TaskConstMeta(
        debugName: "parse_session_ticket",
        argNames: ["ticket"],
      );

  @override
  Future<void> crateApiIrohClientResizeTerminal({
    required TerminalResizeRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_terminal_resize_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_rust_error,
        ),
        constMeta: kCrateApiIrohClientResizeTerminalConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientResizeTerminalConstMeta =>
      const TaskConstMeta(debugName: "resize_terminal", argNames: ["request"]);

  @override
  Future<void> crateApiIrohClientSendTerminalInputToTerminal({
    required TerminalInputRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_terminal_input_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_rust_error,
        ),
        constMeta: kCrateApiIrohClientSendTerminalInputToTerminalConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientSendTerminalInputToTerminalConstMeta =>
      const TaskConstMeta(
        debugName: "send_terminal_input_to_terminal",
        argNames: ["request"],
      );

  @override
  Future<void> crateApiIrohClientStopTerminal({
    required TerminalStopRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_terminal_stop_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_rust_error,
        ),
        constMeta: kCrateApiIrohClientStopTerminalConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientStopTerminalConstMeta =>
      const TaskConstMeta(debugName: "stop_terminal", argNames: ["request"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  (int, int) dco_decode_box_autoadd_record_u_16_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as (int, int);
  }

  @protected
  TerminalCreateRequest dco_decode_box_autoadd_terminal_create_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_terminal_create_request(raw);
  }

  @protected
  TerminalInputRequest dco_decode_box_autoadd_terminal_input_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_terminal_input_request(raw);
  }

  @protected
  TerminalResizeRequest dco_decode_box_autoadd_terminal_resize_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_terminal_resize_request(raw);
  }

  @protected
  TerminalStopRequest dco_decode_box_autoadd_terminal_stop_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_terminal_stop_request(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  (int, int)? dco_decode_opt_box_autoadd_record_u_16_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_record_u_16_u_16(raw);
  }

  @protected
  (int, int) dco_decode_record_u_16_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_u_16(arr[0]), dco_decode_u_16(arr[1]));
  }

  @protected
  RustError dco_decode_rust_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustError(
      code: dco_decode_i_32(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  StreamEvent dco_decode_stream_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return StreamEvent(
      sessionId: dco_decode_String(arr[0]),
      eventType: dco_decode_String(arr[1]),
      data: dco_decode_String(arr[2]),
    );
  }

  @protected
  TerminalCreateRequest dco_decode_terminal_create_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TerminalCreateRequest(
      sessionId: dco_decode_String(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      shellPath: dco_decode_opt_String(arr[2]),
      workingDir: dco_decode_opt_String(arr[3]),
      size: dco_decode_opt_box_autoadd_record_u_16_u_16(arr[4]),
    );
  }

  @protected
  TerminalInputRequest dco_decode_terminal_input_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TerminalInputRequest(
      sessionId: dco_decode_String(arr[0]),
      terminalId: dco_decode_String(arr[1]),
      input: dco_decode_String(arr[2]),
    );
  }

  @protected
  TerminalResizeRequest dco_decode_terminal_resize_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TerminalResizeRequest(
      sessionId: dco_decode_String(arr[0]),
      terminalId: dco_decode_String(arr[1]),
      rows: dco_decode_u_16(arr[2]),
      cols: dco_decode_u_16(arr[3]),
    );
  }

  @protected
  TerminalStopRequest dco_decode_terminal_stop_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TerminalStopRequest(
      sessionId: dco_decode_String(arr[0]),
      terminalId: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  (int, int) sse_decode_box_autoadd_record_u_16_u_16(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_record_u_16_u_16(deserializer));
  }

  @protected
  TerminalCreateRequest sse_decode_box_autoadd_terminal_create_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_terminal_create_request(deserializer));
  }

  @protected
  TerminalInputRequest sse_decode_box_autoadd_terminal_input_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_terminal_input_request(deserializer));
  }

  @protected
  TerminalResizeRequest sse_decode_box_autoadd_terminal_resize_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_terminal_resize_request(deserializer));
  }

  @protected
  TerminalStopRequest sse_decode_box_autoadd_terminal_stop_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_terminal_stop_request(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (int, int)? sse_decode_opt_box_autoadd_record_u_16_u_16(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_record_u_16_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (int, int) sse_decode_record_u_16_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_u_16(deserializer);
    var var_field1 = sse_decode_u_16(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RustError sse_decode_rust_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_i_32(deserializer);
    var var_message = sse_decode_String(deserializer);
    return RustError(code: var_code, message: var_message);
  }

  @protected
  StreamEvent sse_decode_stream_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_eventType = sse_decode_String(deserializer);
    var var_data = sse_decode_String(deserializer);
    return StreamEvent(
      sessionId: var_sessionId,
      eventType: var_eventType,
      data: var_data,
    );
  }

  @protected
  TerminalCreateRequest sse_decode_terminal_create_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_shellPath = sse_decode_opt_String(deserializer);
    var var_workingDir = sse_decode_opt_String(deserializer);
    var var_size = sse_decode_opt_box_autoadd_record_u_16_u_16(deserializer);
    return TerminalCreateRequest(
      sessionId: var_sessionId,
      name: var_name,
      shellPath: var_shellPath,
      workingDir: var_workingDir,
      size: var_size,
    );
  }

  @protected
  TerminalInputRequest sse_decode_terminal_input_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_terminalId = sse_decode_String(deserializer);
    var var_input = sse_decode_String(deserializer);
    return TerminalInputRequest(
      sessionId: var_sessionId,
      terminalId: var_terminalId,
      input: var_input,
    );
  }

  @protected
  TerminalResizeRequest sse_decode_terminal_resize_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_terminalId = sse_decode_String(deserializer);
    var var_rows = sse_decode_u_16(deserializer);
    var var_cols = sse_decode_u_16(deserializer);
    return TerminalResizeRequest(
      sessionId: var_sessionId,
      terminalId: var_terminalId,
      rows: var_rows,
      cols: var_cols,
    );
  }

  @protected
  TerminalStopRequest sse_decode_terminal_stop_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_terminalId = sse_decode_String(deserializer);
    return TerminalStopRequest(
      sessionId: var_sessionId,
      terminalId: var_terminalId,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_record_u_16_u_16(
    (int, int) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_record_u_16_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_terminal_create_request(
    TerminalCreateRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_terminal_create_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_terminal_input_request(
    TerminalInputRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_terminal_input_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_terminal_resize_request(
    TerminalResizeRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_terminal_resize_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_terminal_stop_request(
    TerminalStopRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_terminal_stop_request(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_record_u_16_u_16(
    (int, int)? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_record_u_16_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_record_u_16_u_16((int, int) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.$1, serializer);
    sse_encode_u_16(self.$2, serializer);
  }

  @protected
  void sse_encode_rust_error(RustError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_stream_event(StreamEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.eventType, serializer);
    sse_encode_String(self.data, serializer);
  }

  @protected
  void sse_encode_terminal_create_request(
    TerminalCreateRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_String(self.shellPath, serializer);
    sse_encode_opt_String(self.workingDir, serializer);
    sse_encode_opt_box_autoadd_record_u_16_u_16(self.size, serializer);
  }

  @protected
  void sse_encode_terminal_input_request(
    TerminalInputRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.terminalId, serializer);
    sse_encode_String(self.input, serializer);
  }

  @protected
  void sse_encode_terminal_resize_request(
    TerminalResizeRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.terminalId, serializer);
    sse_encode_u_16(self.rows, serializer);
    sse_encode_u_16(self.cols, serializer);
  }

  @protected
  void sse_encode_terminal_stop_request(
    TerminalStopRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.terminalId, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
