// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < UnboundedSender < StreamEvent > >>>
abstract class ArcUnboundedSenderStreamEvent implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RwLock < HashMap < String , Arc < UnboundedSender < StreamEvent > > > >>>
abstract class HashMapStringArcUnboundedSenderStreamEvent
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RwLock < HashMap < String , TerminalSession > >>>
abstract class HashMapStringTerminalSession implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RwLock < Option < Arc < CommunicationManager > > >>>
abstract class OptionArcCommunicationManager implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RwLock < Option < QuicMessageClientHandle > >>>
abstract class OptionQuicMessageClientHandle implements RustOpaqueInterface {}
