// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `APP_STATE`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppState>>
abstract class AppState implements RustOpaqueInterface {
  OptionArcCommunicationManager get communicationManager;

  HashMapStringArcUnboundedSenderStreamEvent get eventStreams;

  OptionQuicMessageClientHandle get quicClient;

  HashMapStringTerminalSession get sessions;

  set communicationManager(OptionArcCommunicationManager communicationManager);

  set eventStreams(HashMapStringArcUnboundedSenderStreamEvent eventStreams);

  set quicClient(OptionQuicMessageClientHandle quicClient);

  set sessions(HashMapStringTerminalSession sessions);

  static Future<AppState> default_() =>
      RustLib.instance.api.crateApiIrohClientPrivateAppStateDefault();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StreamEventListener>>
abstract class StreamEventListener implements RustOpaqueInterface {
  ArcUnboundedSenderStreamEvent get sender;

  String get sessionId;

  set sender(ArcUnboundedSenderStreamEvent sender);

  set sessionId(String sessionId);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<StreamEventListener> newInstance({
    required String sessionId,
    required ArcUnboundedSenderStreamEvent sender,
  }) => RustLib.instance.api.crateApiIrohClientPrivateStreamEventListenerNew(
    sessionId: sessionId,
    sender: sender,
  );
}
